# this is a sample schema file, you can copy it and change anything you like

# faker config
faker:
  locales:
    - zh_CN
    # - zh_TW
  providers:
    - internet
    - name: my_code
      source: custom_provider.txt

# generator params
params:
  amount: 5
  format: csv
  args:
    separator: '|'

# user's env params, will be passed to generators as context object
env:
  hello: yes!
  and:
    me: oh no!

# data schema
struct:
  student:
    id:
      type: num
      rule: regex
      value: \d{10}
    name:
      rule: eval
      value: fake.name()
    ip:
      rule: eval
      value: fake.ipv4()
    none_test:
      rule: none
    code:
      rule: eval
      value: fake.my_code()
  score:
    id:
      type: int
      rule: foreign
      value: student.id
      args:
        cast: one # one, random
    score:
      type: int
      rule: range
      value: 0...100
    line_test:
      type: float
      rule: eval
      value: str(line.score + 100) + str(line.index)